server:
  port: 8081
  servlet:
    context-path: /chat
spring:
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/ChatService?authSource=admin
      username: root
      password: root
      gridfs:
        database: ChatService
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
