export const FETCH_USER_PROF_REQU = 'FETCH_USER_PROFILE_REQUEST';
export const FETCH_USER_PROF_SUCC = 'FETCH_USER_PROFILE_SUCCESS';
export const FETCH_USER_PROF_FAIL = 'FETCH_USER_PROFILE_FAILURE';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';